#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-fuubar
Version  : 2.1.1
Release  : 8
URL      : https://rubygems.org/downloads/fuubar-2.1.1.gem
Source0  : https://rubygems.org/downloads/fuubar-2.1.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-ruby-progressbar
BuildRequires : rubygem-rubygems-tasks

%description
#Fuubar
[![Gem Version](https://img.shields.io/gem/v/fuubar.svg)](https://rubygems.org/gems/fuubar) ![Rubygems Rank Overall](https://img.shields.io/gem/rt/fuubar.svg) ![Rubygems Rank Daily](https://img.shields.io/gem/rd/fuubar.svg) ![Rubygems Downloads](https://img.shields.io/gem/dv/fuubar/stable.svg) [![Build Status](https://img.shields.io/travis/thekompanee/fuubar/master.svg)](http://travis-ci.org/thekompanee/fuubar) [![Code Climate](https://codeclimate.com/github/thekompanee/fuubar.svg)](https://codeclimate.com/github/thekompanee/fuubar)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n fuubar-2.1.1
gem spec %{SOURCE0} -l --ruby > rubygem-fuubar.gemspec

%build
export LANG=C
gem build rubygem-fuubar.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
fuubar-2.1.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/fuubar-2.1.1
rspec -I.:lib spec/ || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/fuubar-2.1.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/fuubar-2.1.1/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/fuubar-2.1.1/README.md
/usr/lib64/ruby/gems/2.3.0/gems/fuubar-2.1.1/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/fuubar-2.1.1/lib/fuubar.rb
/usr/lib64/ruby/gems/2.3.0/gems/fuubar-2.1.1/lib/fuubar/output.rb
/usr/lib64/ruby/gems/2.3.0/gems/fuubar-2.1.1/spec/fuubar/output_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/fuubar-2.1.1/spec/fuubar_spec.rb
/usr/lib64/ruby/gems/2.3.0/specifications/fuubar-2.1.1.gemspec
