#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-fuubar
Version  : 2.0.0
Release  : 6
URL      : https://rubygems.org/downloads/fuubar-2.0.0.gem
Source0  : https://rubygems.org/downloads/fuubar-2.0.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-ruby-progressbar

%description
#Fuubar
[![Gem Version](https://badge.fury.io/rb/fuubar.png)](https://badge.fury.io/rb/fuubar) [![Build Status](https://secure.travis-ci.org/thekompanee/fuubar.png?branch=master)](http://travis-ci.org/thekompanee/fuubar) [![Code Climate](https://codeclimate.com/github/thekompanee/fuubar.png)](https://codeclimate.com/github/thekompanee/fuubar) [![Code Climate](https://codeclimate.com/github/thekompanee/fuubar/coverage.png)](https://codeclimate.com/github/thekompanee/fuubar)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n fuubar-2.0.0
gem spec %{SOURCE0} -l --ruby > rubygem-fuubar.gemspec

%build
gem build rubygem-fuubar.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
fuubar-2.0.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/fuubar-2.0.0
rspec -I.:lib spec/ || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/fuubar-2.0.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/fuubar-2.0.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/fuubar-2.0.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/fuubar-2.0.0/lib/fuubar.rb
/usr/lib64/ruby/gems/2.3.0/gems/fuubar-2.0.0/spec/fuubar_spec.rb
/usr/lib64/ruby/gems/2.3.0/specifications/fuubar-2.0.0.gemspec
